Repository herbsjs/herbs-cli, pull requests merged in 2022-01, with the labels that each got.

#89 Support for data layer generation with MySQL database
  __tests__/cli-integration.test.js
  package-lock.json
  src/commands/new.js
  src/generators/index.js
  src/generators/src/domain/entities.js
  src/generators/src/domain/usecases/unitTests.js
  src/generators/src/domain/usecases/useCases.js
  src/generators/src/index.js
  src/generators/src/infra/api/graphql.js
  src/generators/src/infra/api/rest.js
  src/generators/src/infra/api/server.js
  src/generators/src/infra/config/index.js
  src/generators/src/infra/database/connection.js
  src/generators/src/infra/database/migrations/migrations.js
  src/generators/src/infra/database/repositories/repositories.js
  src/generators/src/infra/git.js
  src/generators/src/packagejson.js
  src/templates/infra/config/.gitignore.ejs
  src/templates/infra/config/mysql.ejs
  src/templates/infra/data/database/mysql/database.ejs
  src/templates/infra/data/database/mysql/migration.ejs
  src/templates/infra/data/repository/mysql/repository.ejs
  src/templates/mysql.knexFile.ejs
Labels: enhancement, wip

#92 build(dependencies): update git action and dev dependencies
  .eslintrc.json
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/pr.yml
  .gitignore
  package-lock.json
  package.json
Labels: severity-major, dependencies

#93 fix: update dependencies
  package-lock.json
  package.json
  src/generators/src/packagejson.js
Labels: severity-minor, dependencies

#94 Fix/node modules
  __tests__/postgres.test.js
  package-lock.json
  src/generators/src/packagejson.js
Labels: bug, enhancement, severity-major
