Repository herbsjs/herbs-cli, pull requests merged in 2022-06, with the labels that each got.

#131 fix: fix mongodb generator
  .gitignore
  package-lock.json
  package.json
  src/commands/new.js
  src/generators/src/domain/usecases/unitTests.js
  src/generators/src/infra/database/migrations/migrations.js
  src/generators/src/packagejson.js
  src/templates/data/repository/mongo/repository.ejs
  src/templates/domain/useCases/create.ejs
  src/templates/domain/useCases/delete.ejs
  src/templates/domain/useCases/find.ejs
  src/templates/domain/useCases/tests/delete.spec.ejs
  src/templates/domain/useCases/tests/find.spec.ejs
  src/templates/domain/useCases/tests/update.spec.ejs
  src/templates/domain/useCases/update.ejs
  src/templates/infra/api/graphql/index.ejs
  src/templates/infra/api/rest/index.ejs
  src/templates/infra/data/database/mongo/database.ejs
  src/templates/infra/data/repository/mongo/repository.ejs
  src/templates/package.json.ejs
  src/tests/mongodb.test.js
  src/tests/packagejson.test.js
Labels: bug, enhancement, severity-major

#134 fix: now cli uses the same return in find methods
  src/commands/new.js
  src/generators/check-version.js
  src/generators/src/packagejson.js
  src/templates/domain/entities/user.ejs
  src/templates/domain/useCases/create.ejs
  src/templates/domain/useCases/delete.ejs
  src/templates/domain/useCases/find.ejs
  src/templates/domain/useCases/tests/delete.spec.ejs
  src/templates/domain/useCases/tests/find.spec.ejs
  src/templates/domain/useCases/tests/update.spec.ejs
  src/templates/domain/useCases/update.ejs
Labels: enhancement, severity-minor, dependencies

#138 Fix Herbs New ... -git without GIT install.
  src/generators/src/infra/git.js
  src/tests/git.test.js
  src/tests/packagejson.test.js
  src/tests/postgres.test.js
Labels: bug, severity-minor

#137 fix(package json): replace author and project name
  package-lock.json
  src/generators/src/packagejson.js
Labels: bug, severity-minor
